# Generated by Django 3.1.7 on 2021-04-03 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_event', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='help.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='help.group')),
                ('phone', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
